name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'DchaSetupWizard/**'
      - 'FirmwareUpdate/**'
      - 'gradle/**'
      - '*.gradle'
      - 'gradlew*'
      - '*.properties'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
            .gradle/
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Set signing configs
        if: github.event.repository.fork != true
        run: |
          echo "${{ secrets.STORE_FILE }}" | base64 -d > release.jks
          export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
          export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
          export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"

      - name: Build with Gradle
        run: |
          ./gradlew aR --no-daemon
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV
          find {DchaSetupWizard,FirmwareUpdate}/build/outputs/apk/ -type f -name *.apk -exec mv {} . \;

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: CPadGApps-CT3@${{ env.commit }}
          path: ./*.apk
